# --- Main Colors ---
background            #181115
foreground            #eddfe4
cursor                #eddfe4
cursor_text_color     #181115

selection_background  #57404d
selection_foreground  #fbd9ea

url_color             #f4ba9e

# --- ANSI Colors ---
color0                #181115
color1                #ffb4ab
color2                #f4ba9e
color3                #debece
color4                #f9b1db
color5                #f4ba9e
color6                #debece
color7                #eddfe4

color8                #4f4349
color9                #93000a
color10               #653d28
color11               #57404d
color12               #6a3457
color13               #57404d
color14               #653d28
color15               #d3c2c9

# --- Starship Prompt Bubbles ---
color255              #6a3457
color254              #f9b1db
color253              #57404d
color252              #debece
color251              #653d28
color250              #f4ba9e
color249              #93000a
color248              #ffb4ab

color232              #ffd8ec
color233              #501e40
color234              #fbd9ea
color235              #3f2a36
color236              #ffdbcb
color237              #4b2714
color238              #ffdad6
color239              #690005
color240              #ffd8ec

# Matched with unthemed light/dark
color243              #f9b1db
color244              #ffb4ab
color245              #4f4349

# --- UI Elements ---
active_tab_foreground   #501e40
active_tab_background   #f9b1db
inactive_tab_foreground #ffd8ec
inactive_tab_background #6a3457

active_border_color     #f9b1db
inactive_border_color   #9c8d93

# --- Marks ---
mark1_foreground        #37072a
mark1_background        #ffd8ec
mark2_foreground        #291521
mark2_background        #fbd9ea
mark3_foreground        #311303
mark3_background        #ffdbcb
