# --- Main Colors ---
background            #111318
foreground            #e2e2e9
cursor                #e2e2e9
cursor_text_color     #111318

selection_background  #3e4758
selection_foreground  #d9e3f9

url_color             #dcbce1

# --- ANSI Colors ---
color0                #111318
color1                #ffb4ab
color2                #dcbce1
color3                #bdc7dc
color4                #a8c8ff
color5                #dcbce1
color6                #bdc7dc
color7                #e2e2e9

color8                #43474e
color9                #93000a
color10               #563e5c
color11               #3e4758
color12               #264777
color13               #3e4758
color14               #563e5c
color15               #c4c6cf

# --- Starship Prompt Bubbles ---
color255              #264777
color254              #a8c8ff
color253              #3e4758
color252              #bdc7dc
color251              #563e5c
color250              #dcbce1
color249              #93000a
color248              #ffb4ab

color232              #d6e3ff
color233              #07305f
color234              #d9e3f9
color235              #273141
color236              #f9d8fe
color237              #3e2845
color238              #ffdad6
color239              #690005
color240              #d6e3ff

# Matched with unthemed light/dark
color243              #a8c8ff
color244              #ffb4ab
color245              #43474e

# --- UI Elements ---
active_tab_foreground   #07305f
active_tab_background   #a8c8ff
inactive_tab_foreground #d6e3ff
inactive_tab_background #264777

active_border_color     #a8c8ff
inactive_border_color   #8e9099

# --- Marks ---
mark1_foreground        #001b3d
mark1_background        #d6e3ff
mark2_foreground        #121c2b
mark2_background        #d9e3f9
mark3_foreground        #28132f
mark3_background        #f9d8fe
