[General]
height=843
width=1515
x=0
y=0

[Browser]
autoPlayPreviews=true
dirConf=true
floatyUI=true
gridSize=3
lastSession=@Variant(\0\0\0\t\0\0\0\x1\0\0\0\t\0\0\0\x1\0\0\0\b\0\0\0\x1\0\0\0\b\0p\0\x61\0t\0h\0\0\0\n\0\0\0\x30\0\x66\0i\0l\0\x65\0:\0/\0/\0/\0h\0o\0m\0\x65\0/\0\x64\0\x65\0v\0/\0.\0\x63\0o\0n\0\x66\0i\0g)
lastTabIndex=0
lastUsedTag=
listSize=0
overviewStart=false
previewFiles=true
previewerWindow=true
quickSidebarSection=true
restoreSession=true
showActionsBar=true
showHiddenFiles=true
showThumbnails=true
sideBarWidth=216
sidebarSections=13, 1, 3, 2
syncTerminal=true
terminalColorScheme=Maui-Dark
terminalFollowsColorScheme=true
viewType=1
windowTranslucency=false

[Sorting]
foldersFirst=true
group=false
sortBy=11
sortOrder=0
