[colors]
# Background and text colors
background=#181115
foreground=#eddfe4

# Selection colors
selection-background=#57404d
selection-foreground=#fbd9ea

# Cursor colors
cursor=#f9b1db #501e40

# Normal colors (0-7)
regular0=#3b3236
regular1=#ffb4ab
regular2=#f9b1db
regular3=#f4ba9e
regular4=#debece
regular5=#6a3457
regular6=#9c8d93
regular7=#d3c2c9

# Bright colors (8-15)
bright0=#4f4349
bright1=#ffb4ab
bright2=#f9b1db
bright3=#f4ba9e
bright4=#debece
bright5=#6a3457
bright6=#9c8d93
bright7=#eddfe4
